{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hello-kubernetes.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $fullName }}
spec:
  acme:
    email: {{  .Values.cert_email }}
    privateKeySecretRef:
      name: letsencrypt-{{ $fullName }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: contour
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ $fullName }}
spec:
  commonName: {{ .Values.cert_commonName }}
  dnsNames:
    - {{ .Values.cert_commonName }}
  issuerRef:
    name: letsencrypt-{{ $fullName }}
    kind: ClusterIssuer
  secretName:  {{ $fullName }}
{{- end }}