{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hello-kubernetes.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  virtualhost:
    fqdn: {{ .Values.cert_commonName }}
    tls:
      secretName: {{ $fullName }}
  routes:
    - conditions:
        - prefix: /
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
{{- end }}
